modules/admin/controllers/SiteController.php
<?php

namespace app\modules\admin\controllers;


use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\components\BaseController;
use app\models\User;


class SiteController extends BaseController
{


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                     'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Действие по умолчанию
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect(['users/index']);
        }

        $model = new User(['scenario' => 'login']);
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['users/index']);
        } else {
            return $this->render('index', [
                'model' => $model,
            ]);
        }
    }


    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


}

modules/admin/controllers/UsersController.php
<?php

namespace app\modules\admin\controllers;


use Yii;
use app\modules\admin\components\AdminController;
use app\models\User;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;


/**
 * Class UsersController
 * @package app\modules\admin\controllers
 */
class UsersController extends AdminController
{

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'view',
                            'options',
                            'search',
                            'change-password'
                        ],
                        'allow' => true,
                        'roles' => [
                            User::ROLE_ADMIN
                        ],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Действие по умолчанию
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        $searchModel = new User();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    /**
     * Действие создание
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new User(['scenario' => 'create']);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Успешно создано');

            return $this->redirect(['users/index']);
        }

        return $this->render('create', ['model' => $model]);
    }

    /**
     * Действие обновление
     * @return string|\yii\web\Response
     */
    public function actionUpdate($id)
    {
        $model = User::getModel($id);
        $model->setScenario('update');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Успешно обновленно');

            return $this->redirect(['users/index']);
        }
        return $this->render('update', ['model' => $model]);
    }

    /**
     * Действие обновление
     * @return string|\yii\web\Response
     */
    public function actionChangePassword($id)
    {
        $model = User::getModel($id);
        $model->setScenario('change_password');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Успешно обновленно');

            return $this->redirect(['users/index']);
        }
        return $this->render('update', ['model' => $model]);
    }


    /**
     * Действие удаление
     * @return string|\yii\web\Response
     */
    public function actionDelete($id)
    {
        $model = User::getModel($id);
        if($model->delete()) {
            Yii::$app->session->addFlash('success', 'Успешно удалено');
        }
        return $this->redirect(['users/index']);
    }
}

modules/admin/views/layouts/_flash.php
<?php foreach(Yii::$app->session->getAllFlashes() as $type => $messages): ?>
    <?php foreach($messages as $message): ?>
        <div class="alert alert-<?= $type ?>" role="alert">
            <?= $message ?>
        </div>
    <?php endforeach ?>
<?php endforeach ?>

modules/admin/views/layouts/main.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */

use yii\helpers\Html;
use yii\helpers\Url;
use app\modules\admin\assets\AdminAsset;
use \yiister\gentelella\widgets\Menu;

AdminAsset::register($this);
?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <?= Html::csrfMetaTags() ?>

        <?php
        $this->registerLinkTag(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => '/favicon.ico']);
        $this->registerLinkTag(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => '/favicon.ico']);

        ?>

        <title>
            <?= Html::encode($this->title) ?>
        </title>

        <?php $this->head() ?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="nav-<?= !empty($_COOKIE['menuIsCollapsed']) && $_COOKIE['menuIsCollapsed'] == 'true' ? 'sm' : 'md' ?>" >
        <?php $this->beginBody(); ?>
            <div class="container body">

                <div class="main_container">

                    <div class="col-md-3 left_col">
                        <div class="left_col scroll-view">

                            <div class="navbar nav_title" style="border: 0;">
                                <a href="/" class="site_title"><i class="fa fa-paw"></i>
                                    <span>
                                        <? echo Yii::t('admin', 'Control panel') ?>
                                    </span>
                                </a>
                            </div>
                            <div class="clearfix"></div>

                            <br/>

                            <!-- sidebar menu -->
                            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

                                <div class="menu_section">
                                    <?=
                                    Menu::widget(
                                        [
                                            "items" => [
                                                [
                                                    "label" => Yii::t("admin", 'Пользователи'),
                                                    "url" => ["/admin/users/index"],
                                                ],
                                                [
                                                    "label" => "Widgets",
                                                    "icon" => "th",
                                                    "url" => "#",
                                                    "items" => [
                                                        ["label" => "Menu", "url" => ["site/menu"]],
                                                        ["label" => "Panel", "url" => ["site/panel"]],
                                                    ],
                                                ],

                                            ],
                                        ]
                                    )
                                    ?>
                                </div>

                            </div>
                            <!-- /sidebar menu -->
                        </div>
                    </div>


                    <!-- top navigation -->
                    <div class="top_nav">

                        <div class="nav_menu">
                            <nav class="" role="navigation">
                                <div class="nav toggle">
                                    <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                                </div>

                                <?php if(!Yii::$app->user->isGuest) {?>
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="">
                                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                <?php echo Yii::$app->user->identity->username;?>
                                                <span class=" fa fa-angle-down"></span>
                                            </a>
                                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                                <li>
                                                    <a href="<?php echo Url::to(['site/logout']);?>" data-method="post">
                                                        <i class="fa fa-sign-out pull-right"></i>
                                                        Выход
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                <?php }?>
                            </nav>
                        </div>

                    </div>
                    <!-- /top navigation -->

                    <!-- page content -->
                    <div class="right_col" role="main">
                        <div class="clearfix"></div>

                        <?php echo $this->render('_flash');?>

                        <?= $content ?>
                    </div>
                    <!-- /page content -->
                    <!-- footer content -->
                    <footer>
                        <div class="pull-right"></div>
                        <div class="clearfix"></div>
                    </footer>
                    <!-- /footer content -->
                </div>

            </div>

            <div id="custom_notifications" class="custom-notifications dsp_none">
                <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group"></ul>
                <div class="clearfix"></div>
                <div id="notif-group" class="tabbed_notifications"></div>
            </div>
            <!-- /footer content -->
        <?php $this->endBody(); ?>
    </body>
</html>
<?php $this->endPage(); ?>

modules/admin/views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <h1>
        <?= Html::encode($this->title) ?>
    </h1>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <?= $form->field($model, 'username') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox() ?>

            <div class="form-group">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/admin/views/users/change_password.php
<?

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Изменить пароль';
?>


<?php $form = ActiveForm::begin([]); ?>

<?= $form->field($model, 'password_old')->passwordInput(); ?>

<?php $model->password = '';?>
<?= $form->field($model, 'password')->passwordInput(); ?>
<?= $form->field($model, 'password_repeat')->passwordInput(); ?>

<?= Html::submitButton('Изменить', [
    'class' => 'btn btn-primary'
]) ?>

<?php ActiveForm::end(); ?>

modules/admin/views/users/create.php
<?php

$this->title = 'Создание';


echo $this->render('form', ['model' => $model]);

?>

modules/admin/views/users/form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Button;
use kartik\select2\Select2;
use app\models\User;

?>

<?php $form = ActiveForm::begin([
    'id'=>'form',
    'layout' => 'default'
]); ?>


<?php
$model->roles = $model->getRoles();
echo $form->field($model, 'roles')->widget(Select2::classname(), [
    'data' => User::$ROLES_ALL,
    'language' => 'ru',
    'options' => ['placeholder' => 'Выберите роль'],
    'pluginOptions' => [
        'multiple' => true,
        'allowClear' => true
    ],
]);
?>

<?php echo $form->field($model, 'username');?>

<?php
    if($model->isNewRecord) {

        $model->password = '';
        $model->password_repeat = '';

        echo $form->field($model, 'password')->passwordInput();
        echo $form->field($model, 'password_repeat')->passwordInput();
    }
?>

<?php echo $form->field($model, 'is_active')->checkbox();?>

<?php echo Button::widget([
    'label' => $model->isNewRecord ? Yii::t('app', 'Создать') : Yii::t('app', 'Обновить'),
    'options' => ['class' => 'btn btn-primary']
]);
?>
<?php ActiveForm::end();?>

modules/admin/views/users/index.php
<?php
/**
 * Грид пользователей
 * @var $this \yii\web\View
 * @var $dataProvider object DataProvider
 * @var $searchModel object User
 */

use yiister\gentelella\widgets\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\Button;

$this->title = Yii::t('app', 'Пользователи');


echo Html::a(Button::widget([
    'label' => 'Создать',
    'options' => ['class' => 'btn-primary'],
]),  ['users/create']);

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        'id',
        'username',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update}{delete}'
        ]
    ]
]);

modules/admin/views/users/update.php
<?php

use yii\bootstrap\Tabs;
use yii\helpers\Url;

$this->title = 'Редактирование';

echo Tabs::widget([
    'items' => [
        [
            'label' => 'Роли',
            'url' => Url::to(['users/update', 'id' => $model->id]),
            'active' => Url::to() == '/admin/users/update?id='.$model->id ? true : false,
            'content' => $this->render('form', ['model' => $model])
        ],
        [
            'label' => 'Изменить пароль',
            'url' => Url::to(['users/change-password', 'id' => $model->id]),
            'active' => Url::to() == '/admin/users/change-password?id='.$model->id ? true : false,
            'content' => $this->render('change_password', ['model' => $model])
        ],
    ],
]);

?>